openapi: "3.0.2"
info:
  title: roompla
  version: "0"
  description: >
    Plan room occupancies and attendence
servers:
  - description: Your local developer service
    url: http://localhost:5050/v0

security:
  - bearerAuth: []
  
paths:
  /login:
      post:
        summary: Create JWT token for credentials of an account.
        operationId: localLogin
        tags:
          - authentification
        requestBody:
          description: Object with the user ID and password to login with
          required: true
          content:
            application/json:
              schema:
                type: object
                required:
                  - user_id
                  - password
                properties:
                  user_id:
                    type: string
                  password:
                    type: string
        responses:
          "200":
            description: Returns a JSON Web Token (JWT), valid until its expiration time is reached.
            content:
              text/plain:
                schema:
                  type: string
                  description: JSON Web Token (JWT)
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwiZXhwIjoiMTU5MjE0NzE5NiIsImNvcnB1c19ncm91cHMiOlsiYWNhZGVtaWMiLCJpbnRlcm5hbCJdLCJhZG1pbiI6ZmFsc2V9._eVf-gPknBlqobOOB83p2bFjf0ws9-mkqb1UkM4rMRg"

          "401":
            description: Unauthorized