/* tslint:disable */
/* eslint-disable */
/**
 * roompla
 * Plan room occupancies and attendence 
 *
 * The version of the OpenAPI document: 0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginData
 */
export interface LoginData {
    /**
     * 
     * @type {string}
     * @memberof LoginData
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof LoginData
     */
    password: string;
}

export function LoginDataFromJSON(json: any): LoginData {
    return LoginDataFromJSONTyped(json, false);
}

export function LoginDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'password': json['password'],
    };
}

export function LoginDataToJSON(value?: LoginData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'password': value.password,
    };
}


